# Generated by Django 2.1.1 on 2019-07-11 13:26

import converter.storage_backends
from django.db import migrations, models
import fileconverter.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='csv_file',
            field=models.FileField(storage=converter.storage_backends.CsvStorage(), upload_to=fileconverter.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
