# Generated by Django 2.1.1 on 2019-07-08 07:21

import converter.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='csv_file',
            field=models.FileField(storage=converter.storage_backends.CsvStorage(), upload_to='media/'),
        ),
    ]
